frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/wesleystalves/biopeptideos-frontend
    tag: f3aebd8c062d2adb9a2c3fd411073acaaf9ca9a7
    pullPolicy: Always
  service:
    port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/wesleystalves/biopeptideos-backend
    tag: f3aebd8c062d2adb9a2c3fd411073acaaf9ca9a7
    pullPolicy: Always
  service:
    port: 3001
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    NODE_ENV: production
    PORT: "3001"
    # DATABASE_URL e JWT_SECRET vêm do Secret db-secret

ingress:
  enabled: true
  host: peptideosbio.com
  annotations:
    kubernetes.io/ingress.class: traefik
