// Auto-gerado do bundle JS do peptideoshealth.com.br — NÃO editar manualmente
// IDs com dados enriquecidos: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 18, 20, 21, 22, 23, 31, 34, 37, 41, 50, 51, 53, 54, 56, 60, 61, 62, 63, 65, 66]

export type PeptideProtocolPhase = { phase: string; dose: string; units: string; };
export type PeptideProtocol = { title: string; route: string; phases: PeptideProtocolPhase[]; };
export type DosageByIndication = { indication: string; dose: string; frequency: string; duration: string; };
export type PeptideInteraction = { type: 'synergic' | 'compatible' | 'monitor' | 'avoid'; name: string; description: string; };
export type PeptideStack = { name: string; peptides: string[]; goal: string; description: string; };
export type PeptideTimeline = { period: string; description: string; };
export type PeptideReference = { id: number; title: string; source: string; year: string; summary: string; pubmedUrl?: string; };

export type PeptideDetail = {
  peptideId: number; alternativeNames: string[]; classification: string;
  evidenceLevel: string; halfLife: string; reconstitutionDifficulty: string;
  whatIs: string; benefits: string[]; mechanism: string[]; mechanismDetailed: string;
  protocol?: PeptideProtocol; dosageByIndication?: DosageByIndication[];
  reconstitution?: string[]; interactions?: PeptideInteraction[];
  stacks?: PeptideStack[]; timeline?: PeptideTimeline[]; references?: PeptideReference[];
};

export const PEPTIDE_DETAILS: Record<number, PeptideDetail> = {
  1: {
    peptideId: 1,
    alternativeNames: ["5-Amino-1-methylquinoline", "5A1MQ", "NNMT Inhibitor"],
    classification: "Inibidor enzimático de pequena molécula",
    evidenceLevel: "Pré-clínico",
    halfLife: "~6-8 horas (oral)",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O 5-Amino-1MQ é um peptídeo sintético que atua como um inibidor seletivo da enzima Nicotinamida N-metiltransferase (NNMT). Sua função principal é modular o metabolismo energético celular, elevando os níveis intracelulares de NAD+ e, consequentemente, ativando vias metabólicas como as mediadas pelas sirtuínas. Este mecanismo o posiciona como um agente promissor para o estudo de condições metabólicas e preservação de massa magra.",
    benefits: ["Potencializa a queima de gordura e a perda de peso.", "Preserva a massa muscular magra durante a perda de peso.", "Aumenta os níveis intracelulares de NAD+.", "Melhora a sensibilidade à insulina.", "Reduz a inflamação."],
    mechanism: ["Inibe a enzima Nicotinamida N-metiltransferase (NNMT).", "Aumenta os níveis de S-adenosilmetionina (SAM) e NAD+.", "Ativa as sirtuínas (SIRT1), que regulam o metabolismo energético.", "Modula a expressão gênica relacionada ao metabolismo de lipídios e glicose."],
    mechanismDetailed: "A NNMT é uma enzima que metila a nicotinamida, consumindo SAM (S-adenosilmetionina) no processo. Em tecidos adiposos de indivíduos obesos, a NNMT é superexpressa, o que reduz os níveis de SAM e NAD+, comprometendo o metabolismo energético celular. O 5-Amino-1MQ inibe seletivamente essa enzima, restaurando os níveis de SAM e NAD+. Com mais NAD+ disponível, as sirtuínas (especialmente SIRT1) são ativadas, promovendo a oxidação de ácidos graxos, a biogênese mitocondrial e a termogênese. Este mecani",
  },
  2: {
    peptideId: 2,
    alternativeNames: ["Adamax peptide", "ACTH(4-10) analogue", "Heptapeptídeo nootrópico"],
    classification: "Heptapeptídeo sintético (análogo de Semax)",
    evidenceLevel: "Pré-clínico",
    halfLife: "~2-4 horas",
    reconstitutionDifficulty: "Moderada",
    whatIs: "Adamax é um heptapeptídeo nootrópico e neuroprotetor, análogo modificado do Semax, que deriva do fragmento ACTH(4–10). Sua estrutura incorpora um grupo adamantano, o qual otimiza a penetração da barreira hematoencefálica e aumenta a estabilidade metabólica do peptídeo, potencializando seus efeitos cognitivos e protetores neuronais.",
    benefits: ["Melhora da função cognitiva, incluindo memória e aprendizado.", "Aumento da neuroproteção contra danos oxidativos e inflamatórios.", "Potencial para reduzir a ansiedade e o estresse.", "Aprimoramento do foco e da atenção.", "Possível melhora do humor e bem-estar geral."],
    mechanism: ["Modulação da atividade de neurotransmissores como dopamina e serotonina.", "Aumento da expressão de fatores neurotróficos, como o BDNF (fator neurotrófico derivado do cérebro).", "Regulação da plasticidade sináptica e formação de novas conexões neuronais.", "Redução da neuroinflamação e do estresse oxidativo no cérebro.", "Interação com receptores específicos no sistema nervoso central para exercer seus efeitos."],
    mechanismDetailed: "O Adamax atua como um análogo aprimorado do Semax, com a adição de um grupo adamantano que confere maior lipofilia e estabilidade metabólica. Isso permite uma melhor penetração na barreira hematoencefálica, resultando em maior biodisponibilidade cerebral. Uma vez no SNC, modula múltiplos sistemas de neurotransmissores, incluindo dopaminérgico e serotoninérgico, além de estimular a expressão de BDNF, um fator essencial para a sobrevivência neuronal, plasticidade sináptica e neurogênese. A combina",
  },
  3: {
    peptideId: 3,
    alternativeNames: ["Acadesine", "AICA-Riboside", "5-Aminoimidazole-4-carboxamide ribonucleoside"],
    classification: "Análogo nucleosídeo de adenosina",
    evidenceLevel: "Pré-clínico",
    halfLife: "~3-4 horas",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O AICAR é um análogo nucleosídeo de adenosina, um composto endógeno, que atua como um ativador direto da proteína quinase ativada por AMP (AMPK). Sua principal função farmacológica é mimetizar o estado de baixo consumo energético celular, promovendo a regulação metabólica e a biogênese mitocondrial, o que lhe confere propriedades de melhora da resistência física.",
    benefits: ["Aumento da resistência e desempenho físico.", "Potencial para melhorar a função metabólica em condições de repouso.", "Redução da gordura corporal e melhora da composição corporal.", "Proteção contra danos isquêmicos em órgãos.", "Possível aplicação no tratamento de doenças metabólicas como diabetes tipo 2."],
    mechanism: ["Ativação direta da AMPK, uma enzima chave na regulação do metabolismo energético celular.", "Mimetiza o estado de baixo nível de energia celular, induzindo vias metabólicas associadas ao exercício.", "Aumento da captação de glicose e oxidação de ácidos graxos nos músculos.", "Modulação da expressão gênica de enzimas envolvidas no metabolismo energético."],
    mechanismDetailed: "O AICAR é convertido intracelularmente em ZMP (AICA ribotídeo), um análogo do AMP que ativa diretamente a AMPK (proteína quinase ativada por AMP). A AMPK é um sensor energético master que, quando ativado, desencadeia uma cascata de respostas metabólicas: aumento da captação de glicose (independente de insulina), oxidação de ácidos graxos, biogênese mitocondrial e inibição de vias anabólicas energeticamente custosas. Essencialmente, o AICAR 'engana' a célula fazendo-a acreditar que está em um est",
  },
  4: {
    peptideId: 4,
    alternativeNames: ["Anti-Obesity Drug 9604", "hGH Fragment 177-191", "Tyr-hGH177-191"],
    classification: "Fragmento peptídico do hGH (16 aminoácidos)",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~30 minutos",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O AOD-9604 é um peptídeo sintético, um fragmento modificado da região C-terminal do hormônio do crescimento humano (hGH 177-191), projetado para promover a lipólise e inibir a lipogênese sem os efeitos metabólicos sistêmicos do hGH intacto. Sua ação se concentra na mobilização de gordura, distinguindo-o de outros análogos do hGH por não elevar os níveis de IGF-1 ou induzir resistência à insulina.",
    benefits: ["Redução da gordura corporal", "Potencial para melhorar o perfil lipídico", "Ausência de efeitos adversos comuns de GH, como elevação de IGF-1", "Não causa resistência à insulina", "Perfil de segurança favorável em estudos clínicos"],
    mechanism: ["Mimetiza a ação do hormônio do crescimento na regulação do metabolismo lipídico", "Atua especificamente no metabolismo da gordura, sem afetar o crescimento ou o metabolismo da glicose", "Estimula a liberação de ácidos graxos de adipócitos", "Inibe a conversão de nutrientes em gordura de armazenamento"],
    mechanismDetailed: "O AOD-9604 é um fragmento modificado do hGH que retém a atividade lipolítica do hormônio do crescimento sem seus efeitos anabólicos e diabetogênicos. Ele se liga a receptores específicos nos adipócitos, ativando a lipólise (quebra de triglicerídeos em ácidos graxos livres e glicerol) e simultaneamente inibindo a lipogênese (formação de novas moléculas de gordura). Diferentemente do hGH completo, o AOD-9604 não estimula a produção de IGF-1 nem afeta o metabolismo da glicose, o que confere um perf",
  },
  5: {
    peptideId: 5,
    alternativeNames: ["Cibinetide", "ARA 290", "EPO-derived peptide"],
    classification: "Peptídeo não-eritropoiético (11 aminoácidos)",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~2 minutos (IV); efeitos farmacológicos prolongados",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O Ara-290 é um peptídeo não-eritropoiético de 11 aminoácidos, derivado do domínio helix-B da eritropoietina, que atua como um agonista seletivo do receptor de reparo inato (IRR). Sua função principal é modular a inflamação e promover a proteção tecidual sem induzir a eritropoiese, oferecendo um perfil terapêutico distinto para condições como neuropatias.",
    benefits: ["Redução da dor neuropática", "Melhora da função nervosa em neuropatias", "Proteção contra danos teciduais", "Potencial tratamento para doenças autoimunes", "Efeitos anti-inflamatórios localizados"],
    mechanism: ["Ativação do receptor de reparo inato (IRR)", "Modulação de vias de sinalização intracelulares", "Redução da inflamação e apoptose celular", "Promoção da reparação tecidual", "Diferenciação de células progenitoras"],
    mechanismDetailed: "O Ara-290 é derivado da helix-B da eritropoietina e ativa seletivamente o receptor de reparo inato (IRR), um heterodímero composto pelo receptor de EPO e pelo receptor beta comum (CD131). Diferentemente da EPO, o Ara-290 não se liga ao receptor homodimérico de EPO responsável pela eritropoiese, evitando efeitos hematopoiéticos. A ativação do IRR desencadeia vias de sinalização anti-apoptóticas e anti-inflamatórias, incluindo JAK2/STAT5, PI3K/Akt e NF-κB, promovendo sobrevivência celular, redução",
  },
  6: {
    peptideId: 6,
    alternativeNames: ["Body Protection Compound-157", "BPC 15", "Bepecin", "PL 14736", "PL-10"],
    classification: "Pentadecapeptídeo (15 aminoácidos)",
    evidenceLevel: "Pré-clínico",
    halfLife: "~4 horas (subcutâneo)",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O BPC-157 é um peptídeo sintético de 15 aminoácidos, derivado de uma proteína gástrica, que exibe potentes propriedades citoprotetoras e de cicatrização tecidual. Sua função principal reside na promoção da reparação de diversos tecidos, incluindo músculos, tendões e ossos, através de mecanismos que envolvem angiogênese e modulação inflamatória. Estudos pré-clínicos sugerem seu potencial terapêutico em uma ampla gama de condições que envolvem danos teciduais.",
    benefits: ["Acelera a cicatrização de tendões, ligamentos, músculos e ossos.", "Reduz a inflamação e a dor em lesões musculoesqueléticas.", "Promove a angiogênese (formação de novos vasos sanguíneos).", "Protege o trato gastrointestinal contra úlceras e inflamações.", "Pode melhorar a recuperação de lesões nervosas."],
    mechanism: ["Modula a expressão de fatores de crescimento, como o VEGF e o FGF-2.", "Aumenta a produção de óxido nítrico, melhorando o fluxo sanguíneo.", "Interage com o sistema de óxido nítrico para promover a angiogênese.", "Exibe efeitos anti-inflamatórios através da modulação de citocinas.", "Protege as células endoteliais e promove a sua proliferação."],
    mechanismDetailed: "",
  },
  7: {
    peptideId: 7,
    alternativeNames: ["BPC-157 Neuro", "BPC-157 Nootrópico"],
    classification: "Pentadecapeptídeo (15 aminoácidos) — uso nootrópico",
    evidenceLevel: "Pré-clínico",
    halfLife: "~4 horas (subcutâneo)",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O BPC-157 para Neuroproteção é um peptídeo gástrico sintético que atua como um potente agente neuroprotetor e nootrópico. Ele exerce sua função modulando neurotransmissores, promovendo a angiogênese cerebral e ativando vias de sinalização essenciais para o crescimento e a proteção neuronal contra danos. Este peptídeo multifuncional oferece um promissor potencial terapêutico na preservação da saúde cerebral e na recuperação de lesões neurológicas.",
    benefits: ["Proteção contra danos cerebrais", "Melhora do humor e motivação", "Recuperação de lesões no SNC", "Potencial contra neurodegeneração", "Melhora do eixo intestino-cérebro"],
    mechanism: ["Modula o sistema dopaminérgico e serotoninérgico", "Promove angiogênese cerebral", "Protege contra neurotoxicidade", "Ativa vias de sinalização de crescimento neuronal"],
    mechanismDetailed: "O BPC-157 exerce seus efeitos neuroprotetores através da modulação dos sistemas dopaminérgico e serotoninérgico no SNC. Ele protege contra a neurotoxicidade induzida por diversas substâncias, incluindo metanfetaminas, álcool e organofosforados. Promove a angiogênese cerebral, aumentando o suprimento sanguíneo para áreas lesionadas, e ativa vias de sinalização de crescimento neuronal como JAK-2/STAT-3 e Akt. Sua ação no eixo intestino-cérebro, mediada pela modulação do nervo vago e do sistema ent",
  },
  8: {
    peptideId: 8,
    alternativeNames: ["NN9838", "AM833", "Long-acting amylin analogue"],
    classification: "Análogo acilado da amilina",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~160 horas (semanal)",
    reconstitutionDifficulty: "Moderada",
    whatIs: "Cagrilintide é um análogo acilado de ação prolongada do hormônio amilina, que atua como um agonista do receptor de amilina. Sua função principal é promover saciedade e retardar o esvaziamento gástrico, resultando na redução da ingestão alimentar e perda de peso. Este peptídeo sintético foi desenvolvido para mimetizar os efeitos fisiológicos da amilina endógena.",
    benefits: ["Promove perda de peso significativa e sustentada.", "Melhora o controle glicêmico em pacientes com diabetes tipo 2.", "Reduz o apetite e a ingestão calórica.", "Potencial para tratamento da obesidade e sobrepeso.", "Administração semanal conveniente."],
    mechanism: ["Ativa os receptores de amilina (AMY1, AMY2, AMY3) no sistema nervoso central.", "Aumenta a sensação de saciedade e plenitude.", "Retarda o esvaziamento gástrico, prolongando a sensação de saciedade.", "Modula a liberação de glucagon."],
    mechanismDetailed: "A Cagrilintide é um análogo da amilina humana com modificações químicas (acilação com ácido graxo C18) que prolongam drasticamente sua meia-vida, permitindo dosagem semanal. Ela ativa os receptores de amilina (AMY1-3), que são heterodímeros do receptor de calcitonina com proteínas RAMP. No SNC, particularmente na área postrema e núcleo do trato solitário, a ativação desses receptores reduz o apetite e promove saciedade. Perifericamente, retarda o esvaziamento gástrico e suprime a secreção de glu",
  },
  9: {
    peptideId: 9,
    alternativeNames: ["Ala-Glu-Asp-Arg", "AEDR", "Peptídeo biorregulador cardíaco"],
    classification: "Tetrapeptídeo biorregulador sintético",
    evidenceLevel: "Pré-clínico",
    halfLife: "~30-60 minutos",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O Cardiogen é um tetrapeptídeo biorregulador sintético (Ala-Glu-Asp-Arg) que atua como um agente cardioprotetor e reparador celular. Ele modula vias de sobrevivência intracelulares, promovendo a integridade citoesquelética e inibindo a apoptose em cardiomiócitos sob estresse.",
    benefits: ["Suporte à função cardíaca em condições de estresse.", "Potencial para melhorar a recuperação após lesão isquêmica.", "Redução da inflamação em tecido cardíaco.", "Otimização da bioenergética celular cardíaca.", "Proteção contra danos oxidativos no miocárdio."],
    mechanism: ["Modulação da expressão gênica de proteínas envolvidas na integridade celular.", "Ativação de vias de sinalização anti-apoptóticas.", "Estabilização da membrana celular e do citoesqueleto.", "Regulação da homeostase de cálcio intracelular.", "Aumento da atividade de enzimas antioxidantes endógenas."],
    mechanismDetailed: "O Cardiogen, como outros peptídeos biorreguladores desenvolvidos pelo Prof. Khavinson, atua ao nível da regulação epigenética da expressão gênica. O tetrapeptídeo Ala-Glu-Asp-Arg se liga ao DNA em regiões promotoras específicas de genes relacionados à função cardíaca, modulando a transcrição de proteínas essenciais para a integridade do cardiomiócito. Isso inclui proteínas anti-apoptóticas (Bcl-2), enzimas antioxidantes (SOD, catalase), e componentes do citoesqueleto. Além disso, regula a homeos",
  },
  10: {
    peptideId: 10,
    alternativeNames: ["Ala-Glu-Asp", "AED", "Peptídeo biorregulador cartilaginoso"],
    classification: "Tripeptídeo biorregulador sintético",
    evidenceLevel: "Pré-clínico",
    halfLife: "Curta (minutos); efeitos prolongados",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O Cartalax é um tripeptídeo biorregulador sintético (Ala-Glu-Asp) que atua modulando a expressão gênica em condrócitos, promovendo a síntese de componentes da matriz extracelular como colágeno tipo II e agrecan. Sua função principal é a proteção e regeneração da cartilagem articular, com propriedades anti-aging que atuam na preservação da integridade tecidual.",
    benefits: ["Proteção e regeneração da cartilagem articular", "Melhora da função articular e mobilidade", "Propriedades anti-aging celulares", "Modulação da expressão gênica em condrócitos", "Suporte à saúde musculoesquelética"],
    mechanism: ["Modulação da expressão gênica em condrócitos", "Estímulo à síntese de colágeno tipo II e agrecan", "Supressão de sinais pró-degenerativos", "Regulação epigenética da homeostase cartilaginosa"],
    mechanismDetailed: "O Cartalax (AED) é um citomédino que atua modulando a expressão gênica em células cartilaginosas. Ele estimula a síntese de componentes da matriz extracelular como colágeno tipo II e agrecan, enquanto suprime vias de sinalização pró-degenerativas. Também pode atuar como agente senomórfico, suprimindo o fenótipo secretório associado à senescência (SASP) em condrócitos envelhecidos.",
  },
  12: {
    peptideId: 12,
    alternativeNames: ["FPF-1070", "Cerebrolysina"],
    classification: "Mistura peptídica neurotrófica (derivada de suínos)",
    evidenceLevel: "Clínico Fase III",
    halfLife: "~6-8 horas (IM); efeitos prolongados",
    reconstitutionDifficulty: "Fácil",
    whatIs: "A Cerebrolysina é uma mistura peptídica biotecnológica derivada de proteínas cerebrais purificadas de suínos. Contém neuropeptídeos de baixo peso molecular que mimetizam BDNF, GDNF, CNTF e NGF. É um dos tratamentos mais validados clinicamente para AVC isquêmico, demência vascular, Alzheimer e lesões cerebrais traumáticas.",
    benefits: ["Acelera recuperação pós-AVC e traumatismo craniano", "Melhora memória, atenção e cognição em idosos", "Protege contra declínio neurodegenerativo", "Melhora humor e clareza mental", "Estimula regeneração de nervos periféricos"],
    mechanism: ["Proteção contra estresse oxidativo e excitotoxicidade do glutamato", "Estimulação da neuroplasticidade e sinaptogênese", "Melhora do metabolismo energético cerebral", "Inibição da formação de placas amiloides"],
    mechanismDetailed: "A Cerebrolysina atua através de um mecanismo multimodal: protege neurônios contra estresse oxidativo e excitotoxicidade do glutamato; estimula neuroplasticidade e formação de novas sinapses; melhora metabolismo energético cerebral; e inibe formação de placas amiloides e emaranhados neurofibrilares. Seus neuropeptídeos mimetizam a ação de fatores neurotróficos endógenos.",
  },
  14: {
    peptideId: 14,
    alternativeNames: ["CJC-1295 with DAC", "Drug Affinity Complex", "DAC:GRF"],
    classification: "Análogo de GHRH com Drug Affinity Complex",
    evidenceLevel: "Clínico Fase II",
    halfLife: "6-8 dias",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O CJC-1295 DAC é um análogo sintético do hormônio liberador do hormônio do crescimento (GHRH) modificado com um Drug Affinity Complex (DAC) que se liga reversivelmente à albumina sérica, estendendo drasticamente sua meia-vida para 6-8 dias. Isso permite administração semanal e elevação sustentada dos níveis de GH e IGF-1.",
    benefits: ["Liberação sustentada e elevada de GH", "Aumento significativo de IGF-1", "Melhora da composição corporal", "Recuperação muscular acelerada", "Melhora da qualidade do sono"],
    mechanism: ["Ativação sustentada do receptor GHRH na hipófise", "Ligação reversível à albumina via DAC prolongando meia-vida", "Estímulo à liberação pulsátil de GH", "Aumento dos níveis de IGF-1 sistêmico"],
    mechanismDetailed: "O CJC-1295 DAC contém o peptídeo Mod GRF 1-29 conjugado a um Drug Affinity Complex (DAC) que se liga reversivelmente à albumina sérica. Essa modificação estende a meia-vida de ~30 minutos para 6-8 dias, mantendo elevação contínua de GH e IGF-1.",
  },
  15: {
    peptideId: 15,
    alternativeNames: ["Modified GRF 1-29", "Mod GRF", "CJC-1295 without DAC"],
    classification: "Análogo de GHRH (29 aminoácidos modificados)",
    evidenceLevel: "Pré-clínico",
    halfLife: "~30 minutos",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O CJC-1295 NO DAC, também conhecido como Mod GRF 1-29, é um análogo truncado e modificado do GHRH que preserva a liberação pulsátil natural de GH. Sem o Drug Affinity Complex, tem meia-vida curta (~30 min), produzindo pulsos de GH mais fisiológicos e com menos efeitos colaterais como retenção hídrica.",
    benefits: ["Pulsos naturais e fisiológicos de GH", "Menos retenção hídrica que versão com DAC", "Melhora da recuperação muscular", "Melhora da qualidade do sono", "Melhor perfil de efeitos colaterais"],
    mechanism: ["Ativação do receptor GHRH na hipófise anterior", "Estímulo à liberação pulsátil de GH", "Meia-vida curta permite padrão fisiológico de GH", "Quatro substituições estabilizantes (D-Ala2, Gln8, Ala15, Leu27)"],
    mechanismDetailed: "O Mod GRF 1-29 é um análogo do GHRH com quatro substituições de aminoácidos que aumentam sua estabilidade contra degradação enzimática. Sem o DAC, mantém meia-vida curta (~30 min), gerando pulsos agudos de GH similares ao padrão fisiológico.",
  },
  18: {
    peptideId: 18,
    alternativeNames: ["PNB-0408", "N-hexanoic-Tyr-Ile-(6) aminohexanoic amide"],
    classification: "Oligopeptídeo derivado de angiotensina IV",
    evidenceLevel: "Pré-clínico",
    halfLife: "~12-24 horas (oral)",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O Dihexa é um pequeno peptídeo derivado da angiotensina IV, considerado um dos nootrópicos mais potentes já descobertos. Com capacidade de promover sinaptogênese ordens de magnitude superior ao BDNF natural, ele atua via ativação da via HGF/c-Met para reparar e criar novas conexões neurais. Desenvolvido para Alzheimer, é reservado para declínio cognitivo significativo.",
    benefits: ["Potencial de reverter danos cognitivos e perda de memória", "Estimula criação massiva de novas conexões neurais", "Melhora drástica do aprendizado e retenção", "Neuroproteção contra doenças degenerativas", "Melhora da coordenação motora e função executiva"],
    mechanism: ["Agonismo do Fator de Crescimento de Hepatócitos (HGF)", "Ativação do receptor c-Met no cérebro", "Estimulação da formação de espinhas dendríticas", "Fortalecimento de conexões sinápticas existentes"],
    mechanismDetailed: "O Dihexa atua como agonista do HGF e seu receptor c-Met. No cérebro, a sinalização HGF/c-Met é fundamental para desenvolvimento sináptico, sobrevivência neuronal e plasticidade. Estudos demonstraram que é 7 ordens de magnitude mais potente que o BDNF na formação de sinapses, tornando-o o nootrópico mais potente conhecido.",
  },
  20: {
    peptideId: 20,
    alternativeNames: ["Epitalon", "AEDG", "Ala-Glu-Asp-Gly", "Epithalamin sintético"],
    classification: "Tetrapeptídeo biorregulador sintético",
    evidenceLevel: "Pré-clínico",
    halfLife: "Curta (minutos); efeitos epigenéticos prolongados",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O Epithalon é um tetrapeptídeo sintético (Ala-Glu-Asp-Gly) baseado no Epithalamin, um extrato natural da glândula pineal. Sua principal ação é a ativação da telomerase, a enzima responsável por estender os telômeros, conferindo-lhe propriedades anti-aging. Também regula o ciclo circadiano através da modulação da melatonina e exerce efeitos antioxidantes e epigenéticos.",
    benefits: ["Ativação da telomerase e extensão de telômeros", "Regulação do ciclo circadiano e melatonina", "Propriedades antioxidantes celulares", "Modulação epigenética do envelhecimento", "Melhora da qualidade do sono"],
    mechanism: ["Ativação direta da telomerase (hTERT)", "Extensão dos telômeros em células somáticas", "Modulação da produção de melatonina pela glândula pineal", "Regulação epigenética via interação com promotores gênicos", "Proteção contra estresse oxidativo celular"],
    mechanismDetailed: "O Epithalon ativa a telomerase interagindo diretamente com regiões promotoras do gene hTERT, a subunidade catalítica da telomerase. Isso resulta em extensão dos telômeros além do limite de Hayflick. Também modula a produção de melatonina pela glândula pineal e atua na remodelação da cromatina.",
  },
  21: {
    peptideId: 21,
    alternativeNames: ["Proxofim", "FOXO4-D-Retro-Inverso"],
    classification: "Peptídeo senolítico D-retro-inverso",
    evidenceLevel: "Pré-clínico",
    halfLife: "~24-48 horas",
    reconstitutionDifficulty: "Avançada",
    whatIs: "O FOXO4-DRI é um peptídeo senolítico de última geração que elimina seletivamente células senescentes ('células zumbis'). Ele interfere na interação FOXO4-p53, forçando células senescentes à apoptose sem afetar células saudáveis. Em estudos animais, resultou em melhoras drásticas na densidade do pelo, função renal, força física e saúde geral.",
    benefits: ["Eliminação de células senescentes em todo o corpo", "Redução da inflamação sistêmica crônica (inflammaging)", "Melhora da função dos órgãos (rins, fígado)", "Reversão de sinais físicos de envelhecimento", "Aumento da vitalidade física e resistência"],
    mechanism: ["Interrupção da interação FOXO4-p53", "Liberação de p53 para induzir apoptose em células senescentes", "Seletividade: células saudáveis não são afetadas", "Redução do fenótipo secretório associado à senescência (SASP)"],
    mechanismDetailed: "O FOXO4-DRI atua interrompendo a interação entre FOXO4 e p53 em células senescentes. Normalmente, FOXO4 mantém p53 sequestrada no núcleo, impedindo apoptose. O peptídeo compete com FOXO4, liberando p53 para sinalizar morte celular programada. Células saudáveis, que não dependem dessa interação para sobrevivência, não são afetadas.",
  },
  22: {
    peptideId: 22,
    alternativeNames: ["Glycyl-L-histidyl-L-lysine:copper(II)", "Copper peptide", "Lamin", "Iamin"],
    classification: "Tripeptídeo-cobre(II)",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~30 minutos (IV); tópico: contínuo",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O GHK-Cu é um tripeptídeo naturalmente presente no plasma humano, composto por glicil-L-histidil-L-lisina ligado a um íon cobre (II). Descoberto em 1973, seus níveis diminuem com a idade. É um potente agente de remodelação tecidual com propriedades anti-aging, anti-inflamatórias e regenerativas comprovadas.",
    benefits: ["Estimula a síntese de colágeno e elastina na pele.", "Promove crescimento capilar e reduz queda de cabelo.", "Acelera a cicatrização de feridas e lesões.", "Possui propriedades antioxidantes e anti-inflamatórias.", "Reduz linhas finas e rugas, melhorando a textura da pele."],
    mechanism: ["Ativa vias de sinalização de remodelação de matriz extracelular.", "Estimula a produção de metaloproteinases (MMPs) e TIMPs.", "Modula a expressão de mais de 4000 genes humanos.", "Promove angiogênese e atração de células-tronco mesenquimais."],
    mechanismDetailed: "",
  },
  23: {
    peptideId: 23,
    alternativeNames: ["Growth Hormone Releasing Peptide 2", "Pralmorelin", "KP-102"],
    classification: "Hexapeptídeo secretagogo de GH (GHRP)",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~25-30 minutos",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O GHRP-2 é um secretagogo de GH de segunda geração que atua como agonista do receptor de grelina (GHS-R1a), estimulando forte liberação de hormônio do crescimento pela hipófise. É considerado um dos GHRPs mais potentes, com efeitos adicionais no estímulo ao apetite e modulação do eixo somatotrófico.",
    benefits: ["Forte liberação de GH pela hipófise", "Aumento do apetite e ingestão calórica", "Recuperação muscular acelerada", "Melhora da qualidade do sono", "Aumento da densidade óssea"],
    mechanism: ["Agonismo do receptor de grelina (GHS-R1a) na hipófise", "Estímulo à liberação pulsátil de GH", "Aumento moderado de cortisol e prolactina", "Sinergismo com GHRH endógeno ou exógeno"],
    mechanismDetailed: "O GHRP-2 se liga ao receptor de secretagogos de GH (GHS-R1a) na hipófise anterior, desencadeando liberação aguda de GH. Possui maior potência na liberação de GH com menos estímulo de apetite que GHRP-6. Quando combinado com GHRH (como CJC-1295), produz liberação sinérgica significativamente maior.",
  },
  31: {
    peptideId: 31,
    alternativeNames: ["IPA", "NNC 26-0161"],
    classification: "Pentapeptídeo secretagogo de GH (GHRP)",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~2 horas",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O Ipamorelin é um secretagogo de GH altamente seletivo que estimula a liberação de hormônio do crescimento sem causar elevações significativas de cortisol ou prolactina. É considerado o GHRP mais 'limpo', com o melhor perfil de efeitos colaterais entre os secretagogos de GH.",
    benefits: ["Liberação seletiva de GH sem elevar cortisol ou prolactina", "Melhora significativa da qualidade do sono", "Recuperação muscular acelerada", "Melhora da composição corporal", "Perfil de segurança superior entre os GHRPs"],
    mechanism: ["Agonismo seletivo do receptor de grelina (GHS-R1a)", "Liberação de GH sem afetar cortisol, prolactina ou aldosterona", "Preservação do padrão pulsátil natural de GH", "Sinergismo com GHRH exógeno"],
    mechanismDetailed: "O Ipamorelin se liga seletivamente ao receptor GHS-R1a na hipófise, estimulando a liberação de GH de forma dose-dependente. Sua alta seletividade significa que não causa elevações de cortisol ou prolactina em doses terapêuticas. Quando combinado com CJC-1295, produz liberação sinérgica de GH 3-5x maior.",
  },
  34: {
    peptideId: 34,
    alternativeNames: ["Lysine-Proline-Valine", "α-MSH C-terminal tripeptide"],
    classification: "Tripeptídeo anti-inflamatório",
    evidenceLevel: "Pré-clínico",
    halfLife: "~1-2 horas",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O KPV é um tripeptídeo (Lisina-Prolina-Valina) derivado da porção C-terminal do alfa-MSH. Sem propriedades de pigmentação, foca nas potentes capacidades anti-inflamatórias e antimicrobianas do hormônio original. É particularmente eficaz contra doenças inflamatórias intestinais, dermatites e infecções, com perfil de toxicidade quase nulo.",
    benefits: ["Redução potente da inflamação intestinal (Colite, Crohn)", "Melhora de psoríase, eczema e acne", "Acelera cicatrização e reduz cicatrizes", "Propriedades antimicrobianas naturais", "Reduz inchaço e edema tecidual"],
    mechanism: ["Inibição da ativação do NF-κB", "Bloqueio da produção de citocinas pró-inflamatórias", "Propriedades antimicrobianas contra S. aureus e Candida", "Modulação direta intracelular de vias inflamatórias"],
    mechanismDetailed: "O KPV atua principalmente inibindo a ativação do NF-kappaB, o complexo proteico que controla a transcrição de genes inflamatórios. Ele entra nas células e bloqueia a sinalização que leva à produção de citocinas pró-inflamatórias. Além disso, possui propriedades antimicrobianas diretas contra Staphylococcus aureus e Candida albicans.",
  },
  37: {
    peptideId: 37,
    alternativeNames: ["Cathelicidin", "hCAP-18", "CAMP"],
    classification: "Peptídeo antimicrobiano catelicidina (37 aminoácidos)",
    evidenceLevel: "Pré-clínico",
    halfLife: "~2-4 horas",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O LL-37 é o único peptídeo antimicrobiano da família catelicidina em humanos. Produzido por glóbulos brancos e células epiteliais, atua como linha de frente do sistema imunológico inato contra bactérias, vírus e fungos. Além de matar patógenos diretamente ao romper membranas, é um potente imunomodulador que atrai células imunes e regula a resposta inflamatória.",
    benefits: ["Atividade antibacteriana de amplo espectro (incluindo resistentes)", "Ação antiviral e antifúngica potente", "Acelera cicatrização de feridas crônicas", "Modula e fortalece resposta imunológica inata", "Ajuda na reparação de tecidos infectados"],
    mechanism: ["Estrutura anfipática que perfura membranas de microrganismos", "Quimiotaxia — atrai células imunes para o local da infecção", "Neutralização de LPS bacteriano (prevenção de sepse)", "Promoção de angiogênese e reepitelização"],
    mechanismDetailed: "O LL-37 possui uma estrutura anfipática que permite inserção e perfuração de membranas de microrganismos carregados negativamente, levando à lise celular. Como imunomodulador, liga-se a receptores FPR2 para estimular migração celular e liberação de citocinas protetoras, além de neutralizar lipopolissacarídeo bacteriano para prevenir sepse.",
  },
  41: {
    peptideId: 41,
    alternativeNames: ["Mitochondrial Open Reading Frame of the 12S rRNA-c", "Exercício em Frasco"],
    classification: "Peptídeo derivado de mitocôndria (16 aminoácidos)",
    evidenceLevel: "Pré-clínico",
    halfLife: "~4-8 horas",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O MOTS-c é um peptídeo derivado da mitocôndria, chamado de 'exercício em frasco' por mimetizar os efeitos metabólicos da atividade física. É codificado pelo DNA mitocondrial (não nuclear) e atua como mensageiro entre mitocôndria e núcleo celular. Promove flexibilidade metabólica, permitindo alternância eficiente entre queima de glicose e gordura.",
    benefits: ["Aumenta sensibilidade à insulina e metabolismo da glicose", "Promove perda de peso e queima de gordura", "Aumenta resistência física e performance atlética", "Melhora função mitocondrial e biogênese", "Efeitos anti-envelhecimento sistêmicos"],
    mechanism: ["Ativação da via AMPK (sensor de energia celular)", "Aumento da captação de glicose nos músculos", "Aumento da oxidação de ácidos graxos", "Regulação do metabolismo do folato", "Síntese de novos transportadores de glicose (GLUT)"],
    mechanismDetailed: "O MOTS-c ativa a via da proteína quinase ativada por AMP (AMPK), o 'sensor de energia' da célula. Isso aumenta captação de glicose nos músculos e oxidação de ácidos graxos. Também regula metabolismo do folato e aumenta síntese de transportadores de glicose. Com o envelhecimento, os níveis naturais de MOTS-c diminuem, associados à resistência à insulina.",
  },
  50: {
    peptideId: 50,
    alternativeNames: ["Bremelanotide", "Vyleesi"],
    classification: "Agonista de receptor de melanocortina",
    evidenceLevel: "Aprovado (FDA/EMA)",
    halfLife: "~2.7 horas",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O PT-141 (Bremelanotide) é um agonista não-seletivo de receptores de melanocortina aprovado pela FDA para o tratamento do Transtorno do Desejo Sexual Hipoativo (HSDD) em mulheres pré-menopausa. Diferentemente de inibidores de PDE5, atua diretamente no sistema nervoso central, estimulando o desejo sexual através de vias de neurotransmissão.",
    benefits: ["Aumento do desejo sexual em homens e mulheres", "Aprovado pela FDA para HSDD", "Ação central no SNC (não apenas vascular)", "Eficaz em casos refratários a PDE5i", "Melhora da excitação e satisfação sexual"],
    mechanism: ["Agonismo de receptores de melanocortina (MC4R principal)", "Ativação de vias de sinalização no hipotálamo", "Liberação de neuropeptídeos relacionados ao desejo", "Aumento do fluxo sanguíneo genital via mecanismos centrais"],
    mechanismDetailed: "O PT-141 ativa receptores de melanocortina, particularmente MC4R, no hipotálamo e tronco cerebral, modulando neurotransmissores como dopamina e oxitocina para aumentar desejo e excitação sexual. Aprovado pela FDA em 2019 como Vyleesi® na dose de 1.75 mg SC.",
  },
  51: {
    peptideId: 51,
    alternativeNames: ["LY3437943", "Agonista triplo GIP/GLP-1/Glucagon"],
    classification: "Agonista triplo de receptores incretínicos",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~6 dias",
    reconstitutionDifficulty: "Moderada",
    whatIs: "Retatrutide é um agonista triplo dos receptores GIP, GLP-1 e glucagon, representando uma nova classe de peptídeos para o tratamento da obesidade e controle metabólico. Sua ação simultânea nos três receptores promove efeitos sinérgicos na perda de peso, controle glicêmico e metabolismo energético, superando os resultados observados com agonistas simples ou duplos.",
    benefits: ["Perda de peso significativa (até 24% em estudos clínicos)", "Melhora do controle glicêmico", "Redução da gordura hepática", "Melhora dos marcadores cardiovasculares", "Supressão do apetite e aumento da saciedade", "Potencial para tratamento de MAFLD (doença hepática gordurosa)"],
    mechanism: ["Ativação do receptor GLP-1: promove secreção de insulina e suprime glucagon de forma glicose-dependente", "Ativação do receptor GIP: potencializa a secreção de insulina e melhora a sensibilidade à insulina", "Ativação do receptor de Glucagon: aumenta o gasto energético e a oxidação de gordura", "Retardo do esvaziamento gástrico, contribuindo para saciedade", "Efeitos centrais na regulação do apetite"],
    mechanismDetailed: "Retatrutide é o primeiro agonista triplo dos receptores GIP, GLP-1 e glucagon em desenvolvimento clínico avançado. A ativação do GLP-1R promove secreção de insulina glicose-dependente, suprime glucagon e retarda o esvaziamento gástrico. A ativação do GIPR potencializa a secreção de insulina e melhora a sensibilidade periférica. A ativação do receptor de glucagon aumenta o gasto energético hepático e a oxidação de ácidos graxos, contribuindo para uma perda de peso superior à observada com agonist",
  },
  53: {
    peptideId: 53,
    alternativeNames: ["TP-7", "Selanc", "Análogo de Tuftsin"],
    classification: "Heptapeptídeo sintético (análogo de Tuftsin)",
    evidenceLevel: "Clínico Fase III",
    halfLife: "~5-10 minutos (intranasal; efeitos prolongados)",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O Selank é um peptídeo ansiolítico sintético derivado do Tuftsin, aprovado na Rússia para uso clínico. Exerce efeitos ansiolíticos potentes sem sedação ou dependência, através da modulação do sistema GABAérgico e influência nos níveis de BDNF, serotonina e dopamina.",
    benefits: ["Redução da ansiedade sem sedação", "Melhora do humor e estabilidade emocional", "Efeitos nootrópicos (memória e aprendizado)", "Propriedades imunomoduladoras", "Sem potencial de dependência"],
    mechanism: ["Modulação alostérica de receptores GABA-A", "Aumento dos níveis de BDNF", "Regulação de serotonina, dopamina e norepinefrina", "Modulação da expressão gênica de encefalinas", "Propriedades imunomoduladoras via tuftsin"],
    mechanismDetailed: "O Selank modula alostericamente os receptores GABA-A de forma similar a benzodiazepínicos de baixa dose, mas sem sedação ou dependência. Aumenta BDNF, regulando neuroplasticidade. Sua porção tuftsin confere propriedades imunomoduladoras.",
  },
  54: {
    peptideId: 54,
    alternativeNames: ["Ozempic", "Wegovy", "Rybelsus", "GLP-1 RA"],
    classification: "Agonista do receptor GLP-1 (análogo de GLP-1)",
    evidenceLevel: "Aprovado (FDA/EMA)",
    halfLife: "~7 dias",
    reconstitutionDifficulty: "Fácil",
    whatIs: "",
    benefits: ["Redução significativa do peso corporal", "Melhora do controle glicêmico em pacientes com diabetes tipo 2", "Diminuição do risco de eventos cardiovasculares adversos maiores em pacientes com diabetes tipo 2 e doença cardiovascular estabelecida", "Supressão do apetite e aumento da saciedade", "Conveniência de dosagem semanal"],
    mechanism: ["Ativação do receptor de GLP-1, resultando em aumento da secreção de insulina dependente de glicose", "Supressão da secreção de glucagon de forma dependente de glicose", "Retardo do esvaziamento gástrico, contribuindo para a saciedade", "Efeitos diretos no sistema nervoso central, reduzindo o apetite e a ingestão alimentar"],
    mechanismDetailed: "O Semaglutide é um análogo do GLP-1 com 94% de homologia ao GLP-1 humano, modificado com uma cadeia lateral de ácido graxo C18 que se liga à albumina sérica, prolongando sua meia-vida para aproximadamente 7 dias. Ele ativa o receptor GLP-1 (GLP-1R) nas células beta pancreáticas, estimulando a secreção de insulina de forma glicose-dependente e suprimindo a secreção de glucagon. No sistema nervoso central, atua nos núcleos hipotalâmicos e no tronco cerebral para reduzir o apetite e a ingestão alim",
  },
  56: {
    peptideId: 56,
    alternativeNames: ["MEHFPGP", "Análogo ACTH(4-10)"],
    classification: "Heptapeptídeo sintético (análogo de ACTH 4-10)",
    evidenceLevel: "Clínico Fase III",
    halfLife: "~3-5 minutos (intranasal; efeitos 20-24h)",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O Semax é um neuropeptídeo sintético derivado do fragmento ACTH(4-10) com potentes propriedades nootrópicas e neuroprotetoras. Aprovado na Rússia, melhora cognição, memória e aprendizado sem elevar cortisol. Atua aumentando BDNF e modulando neurotransmissores.",
    benefits: ["Melhora da memória e velocidade de processamento", "Neuroproteção contra danos isquêmicos", "Aumento do BDNF cerebral", "Melhora do foco e atenção", "Sem efeitos hormonais (não eleva cortisol)"],
    mechanism: ["Aumento da expressão de BDNF", "Modulação dopaminérgica e serotoninérgica", "Proteção contra excitotoxicidade", "Melhora da microcirculação cerebral", "Regulação da expressão gênica neuronal"],
    mechanismDetailed: "O Semax retém propriedades neurotrópicas do ACTH sem efeitos endócrinos. Aumenta BDNF, promove neuroplasticidade e modula sistemas dopaminérgico e serotoninérgico. Doses intranasais de 0.25-1.0 mg produzem efeitos nootrópicos sustentados por 20-24h.",
  },
  60: {
    peptideId: 60,
    alternativeNames: ["Elamipretide", "Bendavia", "MTP-131"],
    classification: "Tetrapeptídeo mitocondrial",
    evidenceLevel: "Clínico Fase III",
    halfLife: "~4-6 horas",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O SS-31 (Elamipretide) é um peptídeo inovador que tem como alvo direto as mitocôndrias. Diferente de antioxidantes comuns, atua na fonte otimizando a eficiência mitocondrial e prevenindo produção excessiva de danos oxidativos. Eficaz em tecidos com alta demanda energética (coração, cérebro, rins), representa um dos bioenergéticos mais potentes para longevidade.",
    benefits: ["Melhora significativa da função e energia mitocondrial", "Proteção potente do coração e rins contra danos oxidativos", "Aumento da resistência física e recuperação muscular", "Efeitos neuroprotetores e melhora da clareza mental", "Redução da inflamação de origem mitocondrial"],
    mechanism: ["Ligação seletiva à cardiolipina mitocondrial", "Otimização da cadeia de transporte de elétrons", "Redução do vazamento de elétrons (radicais livres)", "Aumento da produção de ATP", "Manutenção da estrutura física mitocondrial"],
    mechanismDetailed: "O SS-31 liga-se seletivamente à cardiolipina, um fosfolipídio único da membrana mitocondrial interna. Ao estabilizar a cardiolipina, otimiza a cadeia de transporte de elétrons, reduz vazamento de elétrons e aumenta eficiência na produção de ATP. Também ajuda a manter a estrutura física das cristas mitocondriais.",
  },
  61: {
    peptideId: 61,
    alternativeNames: ["BI 456906", "Agonista dual GLP-1/Glucagon"],
    classification: "Agonista dual de receptores GLP-1/GCGR",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~5-7 dias",
    reconstitutionDifficulty: "Moderada",
    whatIs: "O Survodutide é um peptídeo agonista dual de próxima geração que atua nos receptores de GLP-1 (peptídeo-1 semelhante ao glucagon) e GCGR (receptor de glucagon), projetado para modular vias metabólicas cruciais. Este mecanismo de ação combinado visa promover a perda de peso e melhorar a saúde metabólica, sendo desenvolvido para o tratamento de obesidade e doenças hepáticas gordurosas não alcoólicas (NAFLD/NASH).",
    benefits: ["Promove perda de peso significativa e sustentada.", "Melhora o controle glicêmico em pacientes com diabetes tipo 2.", "Reduz a esteatose hepática e a inflamação em NAFLD/NASH.", "Potencial para reverter a fibrose hepática em NASH.", "Melhora parâmetros metabólicos como colesterol e triglicerídeos."],
    mechanism: ["Agonismo do receptor do peptídeo-1 semelhante ao glucagon (GLP-1R), aumentando a secreção de insulina dependente de glicose e suprimindo o glucagon.", "Agonismo do receptor do glucagon (GCGR), promovendo a lipólise e a oxidação de ácidos graxos no fígado.", "Ação sinérgica GLP-1/GCGR para otimizar a perda de peso e melhorar a sensibilidade à insulina.", "Redução do apetite e aumento da saciedade via GLP-1R no sistema nervoso central.", "Modulação do metabolismo lipídico e hepático através da ativação do GCGR."],
    mechanismDetailed: "O Survodutide é um agonista dual que combina a ativação do receptor GLP-1 e do receptor de glucagon em uma única molécula peptídica. A ativação do GLP-1R promove secreção de insulina glicose-dependente, suprime glucagon pós-prandial, retarda o esvaziamento gástrico e reduz o apetite via SNC. A ativação do GCGR estimula a lipólise hepática, aumenta a oxidação de ácidos graxos e o gasto energético, e reduz a esteatose hepática. A combinação desses dois mecanismos resulta em perda de peso superior ",
  },
  62: {
    peptideId: 62,
    alternativeNames: ["Thymosin Beta-4", "Tβ4", "Ac-LKKTETQ"],
    classification: "Peptídeo de 43 aminoácidos (fragmento ativo: 7 aa)",
    evidenceLevel: "Clínico Fase II",
    halfLife: "~2-3 horas",
    reconstitutionDifficulty: "Fácil",
    whatIs: "O TB-500 é um peptídeo sintético derivado da Timosina Beta-4 (Tβ4), uma proteína presente em quase todas as células humanas. Reproduz o domínio ativo de ligação à actina, promovendo migração celular, angiogênese, redução da inflamação e aceleração da cicatrização. Sua ação é sistêmica — não precisa ser aplicado localmente.",
    benefits: ["Cicatrização acelerada de feridas e lesões", "Redução da inflamação", "Angiogênese (novos vasos sanguíneos)", "Melhora da flexibilidade e mobilidade", "Recuperação muscular e tendínea"],
    mechanism: ["Regulação da actina e motilidade celular", "Promoção de migração celular e angiogênese", "Redução da inflamação via modulação de citocinas", "Regulação de metaloproteinases (MMPs)", "Ação sistêmica"],
    mechanismDetailed: "O TB-500 reproduz o domínio de ligação à actina da Tβ4, regulando polimerização de actina e promovendo migração celular. Estimula angiogênese e reduz inflamação. Estudos demonstraram aumento de 42-61% na re-epitelização de feridas.",
  },
  63: {
    peptideId: 63,
    alternativeNames: ["Egrifta", "TH9507", "Trans-3-hexenoic acid GHRH(1-44)"],
    classification: "Análogo sintético de GHRH (44 aminoácidos + ácido hexenóico)",
    evidenceLevel: "Aprovado (FDA/EMA)",
    halfLife: "~26-38 minutos",
    reconstitutionDifficulty: "Moderada",
    whatIs: "A Tesamorelina é um análogo de GHRH aprovado pelo FDA para lipodistrofia em HIV. Estimula liberação pulsátil e fisiológica de GH pela hipófise, com eficácia inigualável na redução de gordura visceral. A adição do ácido hexenóico aumenta estabilidade e resistência à degradação enzimática.",
    benefits: ["Redução drástica da gordura abdominal visceral", "Aumento dos níveis naturais de GH e IGF-1", "Melhora do perfil lipídico", "Melhora da cognição em idosos", "Não causa aumento significativo da fome"],
    mechanism: ["Ligação aos receptores de GHRH na hipófise anterior", "Estímulo à síntese e liberação pulsátil de GH", "GH atua no fígado para produzir IGF-1", "Ação direta nos adipócitos para lipólise visceral"],
    mechanismDetailed: "A Tesamorelina liga-se aos receptores de GHRH na hipófise anterior, estimulando síntese e liberação pulsátil de GH. O GH atua no fígado para produzir IGF-1 e diretamente nos adipócitos para estimular lipólise, com afinidade particular pelo tecido adiposo visceral. Diferente dos GHRPs, não estimula significativamente o apetite.",
  },
  65: {
    peptideId: 65,
    alternativeNames: ["Tα1", "Thymalfasin", "Zadaxin"],
    classification: "Peptídeo imunomodulador (28 aminoácidos)",
    evidenceLevel: "Aprovado (FDA/EMA)",
    halfLife: "~2 horas",
    reconstitutionDifficulty: "Fácil",
    whatIs: "A Timosina Alfa-1 é um peptídeo imunomodulador de 28 aminoácidos originalmente isolado do timo. Aprovada em vários países como Zadaxin® para hepatite B crônica e como adjuvante em imunodeficiências. Estimula células T, ativa células NK e dendríticas, e modula a resposta imune.",
    benefits: ["Fortalecimento da resposta imune", "Atividade antiviral", "Maturação de células T e ativação de NK", "Adjuvante em vacinas e imunoterapia", "Modulação da inflamação crônica"],
    mechanism: ["Estimulação da maturação de células T via TLR9", "Ativação de células dendríticas", "Aumento da atividade citotóxica de NK", "Modulação de citocinas (IL-2, IFN-γ, IL-12)", "Ação anti-inflamatória"],
    mechanismDetailed: "A Tα1 ativa receptores Toll-like (TLR2, TLR9) em células dendríticas, promovendo maturação e apresentação de antígenos. Estimula diferenciação de células T e produção de citocinas Th1. Aprovada em 30+ países como Zadaxin®.",
  },
  66: {
    peptideId: 66,
    alternativeNames: ["Mounjaro", "Zepbound", "LY3298176", "Agonista dual GIP/GLP-1"],
    classification: "Agonista dual de receptores GIP/GLP-1",
    evidenceLevel: "Aprovado (FDA/EMA)",
    halfLife: "~5 dias",
    reconstitutionDifficulty: "Fácil",
    whatIs: "",
    benefits: ["Redução significativa do peso corporal em pacientes com sobrepeso ou obesidade.", "Melhoria do controle glicêmico em pacientes com diabetes tipo 2.", "Diminuição da hemoglobina glicada (HbA1c).", "Potencial para redução do risco cardiovascular.", "Efeitos benéficos na pressão arterial e perfil lipídico."],
    mechanism: ["Ativação dos receptores do peptídeo insulinotrópico dependente de glicose (GIP).", "Ativação dos receptores do peptídeo semelhante ao glucagon 1 (GLP-1).", "Aumento da secreção de insulina dependente de glicose.", "Supressão da secreção de glucagon.", "Retardo do esvaziamento gástrico e aumento da saciedade."],
    mechanismDetailed: "",
  },
};

export function getPeptideDetail(id: number): PeptideDetail | undefined {
  return PEPTIDE_DETAILS[id];
}
